export const CREDENTIAL_CENTER_ABI = [
  "function owner() external view returns (address)",
  "function authorizeInstitution(address institution, string name_) external",
  "function revokeInstitution(address institution) external",
  "function getInstitution(address institution) external view returns (string name_, bool isActive)",
  "function listInstitutions() external view returns (address[] addrs, string[] names, bool[] actives)",
  "function isInstitution(address institution) external view returns (bool)",
  "function getIssuerMintedCount(address issuer) external view returns (uint256)",
  "function applyForIssuer(string metadataCID) external returns (uint256)",
  "function getMyIssuerApplication() external view returns (uint256 id, tuple(address applicant,string metadataCID,uint256 createdAt,uint8 status) application)",
  "function getIssuerApplications() external view returns (uint256[] ids, tuple(address applicant,string metadataCID,uint256 createdAt,uint8 status)[] applications)",
  "function approveIssuer(address applicant) external",
  "function rejectIssuer(address applicant, string reason) external",
  "function submitClaim(address institution, string title, uint8 category, string reviewCid, string privateCid) external returns (uint256)",
  "function getMyClaims() external view returns (uint256[] ids, tuple(address institution,address student,string institutionName,string title,uint8 category,string reviewCid,string privateCid,uint256 createdAt,uint256 decidedAt,uint256 tokenId,uint8 status,string rejectReason)[] claims_)",
  "function getPendingClaims() external view returns (uint256[] ids, tuple(address institution,address student,string institutionName,string title,uint8 category,string reviewCid,string privateCid,uint256 createdAt,uint256 decidedAt,uint256 tokenId,uint8 status,string rejectReason)[] claims_)",
  "function rejectClaim(uint256 claimId, string reason) external",
  "function approveClaimAndMint(uint256 claimId, string publicImageCid, bool displayed) external returns (uint256)",
  "function issueOffer(address student, string title, uint8 category, string publicImageCid, string attachmentCid) external returns (uint256)",
  "function getOffersFor(address student) external view returns (uint256[] ids, tuple(address issuer,address student,string issuerName,string title,uint8 category,string publicImageCid,string attachmentCid,uint256 createdAt,uint8 status)[] offers_)",
  "function getOffer(uint256 offerId) external view returns (tuple(address issuer,address student,string issuerName,string title,uint8 category,string publicImageCid,string attachmentCid,uint256 createdAt,uint8 status) offer)",
  "function acceptOffer(uint256 offerId, string privateCid, bool displayed) external returns (uint256)",
  "function rejectOffer(uint256 offerId, bool shouldBlock) external",
  "function blockIssuer(address issuer) external",
  "function unblockIssuer(address issuer) external",
  "function getMyBlockedIssuers() external view returns (address[] issuers)",
  "function isBlocked(address student, address issuer) external view returns (bool)",
  "function getMyTokens() external view returns (uint256[] ids, tuple(uint256 offerId,address issuer,string issuerName,string title,uint8 category,string publicImageCid,string privateCid,bool displayed)[] tokens_)",
  "function getTokensOf(address user) external view returns (uint256[] ids, tuple(uint256 offerId,address issuer,string issuerName,string title,uint8 category,string publicImageCid,string privateCid,bool displayed)[] tokens_)",
  "function getToken(uint256 tokenId) external view returns (tuple(uint256 offerId,address issuer,string issuerName,string title,uint8 category,string publicImageCid,string privateCid,bool displayed))",
  "function setDisplayed(uint256 tokenId, bool displayed) external",
  "function setDisplayedMany(uint256[] tokenIds, bool displayed) external",
  "function burn(uint256 tokenId) external",
  "function burnMany(uint256[] tokenIds) external",
  "event InstitutionAuthorized(address indexed institution, string name)",
  "event InstitutionRevoked(address indexed institution)",
  "event IssuerApplied(uint256 indexed applicationId, address indexed applicant, string metadataCID)",
  "event IssuerApproved(uint256 indexed applicationId, address indexed applicant)",
  "event IssuerRejected(uint256 indexed applicationId, address indexed applicant, string reason)",
  "event OfferIssued(uint256 indexed offerId, address indexed issuer, address indexed student)",
  "event OfferAccepted(uint256 indexed offerId, uint256 indexed tokenId, address indexed student)",
  "event OfferRejected(uint256 indexed offerId, address indexed student, bool blocked)",
  "event ClaimSubmitted(uint256 indexed claimId, address indexed institution, address indexed student)",
  "event ClaimRejected(uint256 indexed claimId, address indexed institution, address indexed student, string reason)",
  "event ClaimApproved(uint256 indexed claimId, uint256 indexed tokenId, address indexed student)",
  "event IssuerBlocked(address indexed student, address indexed issuer)",
  "event IssuerUnblocked(address indexed student, address indexed issuer)",
  "event DisplayUpdated(uint256 indexed tokenId, bool displayed)"
];
