export const ISSUER_BATCH_ABI = [
  "function owner() external view returns (address)",
  "function credentialCenter() external view returns (address)",
  "function archivesRegistry() external view returns (address)",
  "function getIssuerStats(address issuer_) external view returns (uint256 templateCount, uint256 issuedCount, uint256 unclaimed)",
  "function getBatchCIDs() external view returns (string[] batchCIDs)",
  "function getBatchRoots() external view returns (bytes32[] batchRoots)",
  "function hasClaimed(address user, uint256 batchIndex) external view returns (bool)",
  "function createTemplate(string templateId, bool hasPrivateAttachment, string schemaCID) external returns (bytes32)",
  "function deactivateTemplate(string templateId) external",
  "function getMyTemplates() external view returns (bytes32[] ids, tuple(address issuer,string templateId,bool hasPrivateAttachment,string schemaCID,uint256 createdAt,bool isActive)[] templates_)",
  "function createBatchIssuance(bytes32 merkleRoot, string templateId, string distributionCID, uint256 total) external returns (bytes32)",
  "function getMyTokens() external view returns (uint256[] ids, tuple(address issuer,string issuerName,string templateId,string attachmentCID,bool displayed)[] tokens_, string[] uris)",
  "function getTokensOf(address user) external view returns (uint256[] ids, tuple(address issuer,string issuerName,string templateId,string attachmentCID,bool displayed)[] tokens_, string[] uris)",
  "function getMyBatches() external view returns (bytes32[] roots, tuple(bytes32 merkleRoot,bytes32 templateIdHash,string templateId,address issuer,string distributionCID,uint256 total,uint256 claimed,uint256 createdAt,bool isActive)[] batches)",
  "function getBatch(bytes32 merkleRoot) external view returns (tuple(bytes32 merkleRoot,bytes32 templateIdHash,string templateId,address issuer,string distributionCID,uint256 total,uint256 claimed,uint256 createdAt,bool isActive) batch)",
  "function claim(bytes32 merkleRoot, string tokenURI_, string attachmentCID, bytes32[] proof) external returns (uint256)",
  "function setDisplayed(uint256 tokenId, bool displayed) external",
  "function setDisplayedMany(uint256[] tokenIds, bool displayed) external",
  "function burn(uint256 tokenId) external",
  "function burnMany(uint256[] tokenIds) external",
  "function tokenURI(uint256 tokenId) external view returns (string)",
  "function getToken(uint256 tokenId) external view returns (tuple(address issuer,string issuerName,string templateId,string attachmentCID,bool displayed) token)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event TemplateCreated(bytes32 indexed templateIdHash, address indexed issuer, string templateId, bool hasPrivateAttachment)",
  "event TemplateDeactivated(bytes32 indexed templateIdHash, address indexed issuer, string templateId)",
  "event BatchIssuanceCreated(bytes32 indexed merkleRoot, bytes32 indexed templateIdHash, address indexed issuer, uint256 total)",
  "event BatchClaimed(bytes32 indexed merkleRoot, address indexed user, uint256 indexed tokenId, string attachmentCID)",
  "event DisplayUpdated(uint256 indexed tokenId, bool displayed)",
  "event Burned(uint256 indexed tokenId, address indexed owner)"
];
