export const NOTARY_ABI = [
  "function createRecord(string _title, string _hash, address _participant, uint256 _expiryTime) external returns (uint256)",
  "function setSeedEnvelope(string _envelope) external",
  "function getSeedEnvelope(address _user) external view returns (string)",
  "function signRecord(uint256 _id) external",
  "function getHistory(address _user) external view returns (uint256[] ids, tuple(string title,string ipfsHash,uint256 blockHeight,address initiator,address participant,bool isFinalized,uint256 expiryTime)[] records)",
  "function getRecord(uint256 _id) external view returns (tuple(string title,string ipfsHash,uint256 blockHeight,address initiator,address participant,bool isFinalized,uint256 expiryTime) record)",
  "function getMyHistory() external view returns (uint256[] ids, tuple(string title,string ipfsHash,uint256 blockHeight,address initiator,address participant,bool isFinalized,uint256 expiryTime)[] records)",
  "function recordCount() external view returns (uint256)",
  "function addFileRecord(string _cid, string _nameEnc, string _categoryEnc, string _mime, uint256 _size, uint256 _createdAt) external returns (uint256)",
  "function addFileRecordV2(string _cid, string _nameEnc, string _categoryEnc, string _mime, uint256 _size, uint256 _createdAt, uint256 _folderId) external returns (uint256)",
  "function getMyFiles() external view returns (uint256[] ids, tuple(string cid,string nameEnc,string categoryEnc,string mime,uint256 size,uint256 createdAt)[] files)",
  "function getFiles(address _user) external view returns (uint256[] ids, tuple(string cid,string nameEnc,string categoryEnc,string mime,uint256 size,uint256 createdAt)[] files)",
  "function getMyFilesV2() external view returns (uint256[] ids, tuple(string cid,string nameEnc,string categoryEnc,string mime,uint256 size,uint256 createdAt)[] files, uint256[] folderIds)",
  "function getFilesV2(address _user) external view returns (uint256[] ids, tuple(string cid,string nameEnc,string categoryEnc,string mime,uint256 size,uint256 createdAt)[] files, uint256[] folderIds)",
  "function moveFiles(uint256[] fileIds, uint256 targetFolderId) external",
  "function deleteFiles(uint256[] fileIds) external",
  "function addCategory(string _name) external returns (uint256)",
  "function getMyFolders() external view returns (uint256[] folderIds, string[] names)",
  "function deleteFolder(uint256 folderId) external",
  "function getUserCategories() external view returns (string[] categories)",
  "event RecordCreated(uint256 indexed id,address indexed initiator,address indexed participant,string title,string ipfsHash,uint256 blockHeight,uint256 expiryTime,bool isFinalized)",
  "event RecordSigned(uint256 indexed id,address indexed participant)",
  "event SeedEnvelopeUpdated(address indexed user)",
  "event CategoryAdded(address indexed user,uint256 indexed index,string name)",
  "event ArchiveFileRecorded(address indexed user,uint256 indexed id,string cid,string nameEnc,string categoryEnc,string mime,uint256 size,uint256 createdAt)",
  "event FilesMoved(address indexed owner,uint256[] fileIds,uint256 indexed targetFolderId)",
  "event FilesDeleted(address indexed owner,uint256[] fileIds)",
  "event FolderDeleted(address indexed user,uint256 indexed folderId,string name)"
];
